---
- name: variable precedence test
  hosts: webservers
  tasks:
    - include_vars:
        file: "{{ item }}"
      with_items:
        - "group_vars/all/all.yml"
        #- "group_vars/{{ env }}/vault.yml" # likely will use "group_vars/{{ app_name }}/{{ env_dtup }}/vault.yml"
        #- "group_vars/{{ env }}/vars.yml" # likely will use "group_vars/{{ app_name }}/{{ env_dtup }}/vars.yml"
        # later will change to something like: #- "group_vars/{{ app_name }}/{{ env_dtup }}/vars.yml"
        - "group_vars/ARISInter/DEV/vars.yml"
        
#  tags: always

  
#- name: install apache and wlplugin binary
#  hosts: webservers
#  ###  become_user: "{{super_user}}"
#  any_errors_fatal: True
#  roles:
#    - apache_wlplugin_binary
    

- name: steup app in appache
  hosts: webservers
  ###  become_user: "{{ apache_user }}"
  any_errors_fatal: True
  roles:
    - setup_app_in_Apache