---
- name: variable precedence test
  hosts: och_linux
  tasks:
    - include_vars:
        file: "{{ item }}"
      with_items:
        - "group_vars/{{ env }}/vault.yml"
        - "group_vars/{{ env }}/vars.yml"

- name: Create Pre-requisites
  hosts: och_linux
  become_user: "{{super_user}}"
  any_errors_fatal: True
  roles:
    - common
  vars:
    create_full_filesystem: True
    app_user_create: True
    download_library_yum: False
    
- name: Stop websphere application
  hosts: och_linux
  become_user: "{{app_user}}"
  any_errors_fatal: True
  roles: 
    - websphere
  vars: 
    stop_was: True
  tags: stop_was
  
- name: Start websphere application
  hosts: och_linux
  become_user: "{{app_user}}"
  any_errors_fatal: True
  roles: 
    - websphere
  vars: 
    start_was: True
  tags: start_was