---
- name: variable precedence test
  hosts: siebel1_linux
  tasks:
    - include_vars:
        file: "{{ item }}"
      with_items:
        - "group_vars/{{ env }}/vault.yml"
        - "group_vars/{{ env }}/vars.yml"

- name: Create Pre-requisites
  hosts: siebel1_linux
  become_user: "{{super_user}}"
  any_errors_fatal: True
  roles:
    - common
  vars:
    create_full_filesystem: False
    app_user_create: False    
    download_library_yum: False