#  this task cannot be skipped for now even /etc/ansible/apache_source/ApacheARIS_Inter/src/ is copied in next task, because the destination is different. 
# imporvement can be made if httpd conf related files directly reference to this file
- name: copy front end cert file
  copy:
    #src: /etc/ansible/apache_source/ApacheARIS_Inter/src/httpd-ssl/certs/www.test.apps.rus.mto.gov.on.ca.crt.pem
    src: "{{ src_cert_path }}/{{ src_cert_file }}"
    #dest: /etc/pki/tls/certs/www.test.apps.rus.mto.gov.on.ca.crt.pem
    dest: "{{ dest_cert_path }}/{{ dest_cert_file }}"
    
- name: copy front end key file
  copy:
    #src: /etc/ansible/apache_source/ApacheARIS_Inter/src/httpd-ssl/private/www.test.apps.rus.mto.gov.on.ca.key.pem
    src: "{{ src_key_path }}/{{ src_key_file }}"
    #dest: /etc/pki/tls/private/www.test.apps.rus.mto.gov.on.ca.key.pem
    dest: "{{ dest_key_path }}/{{ dest_key_file }}"

#  this task cannot be skipped for now even /etc/ansible/apache_source/ApacheARIS_Inter/src/ is copied in next task, because the destination is different.
- name: copy app httpd conf files
  copy: 
    #src: /etc/ansible/apache_source/ApacheARIS_Inter/for_httpd_conf.d/
    src: "{{ src_httd_conf_d_dir }}"
    #dest: /etc/httpd/conf.d
    dest: "{{ dest_httd_conf_d_dir }}"

- name: copy apache_source/tso_managed/ env_dtup /src/ that includes tsobin/passphrase.sh for open key file
  copy:
    #src: /etc/ansible/apache_source/tso_managed/DEV/src/
    src: "{{ src_app_I_dir }}"
    #dest: /opt/app-root/src/ #this must match location of passphrase.sh in ssl.conf 
    dest: "{{ dest_app_I_dir }}"
    mode: 0740


