---
# tasks file for apache_wlplugin
- include_tasks: install_apache_binary.yml
  when: install_apache_binary | default(False) == True
  
- include_tasks: prepare_WebLogic_plugin_binary.yml
  when:  prepare_WebLogic_plugin_binary | default(False) == True
  
- include_tasks: remove_then_add_static_content.yml
  when:  remove_then_add_static_content | default(False) == True

- include_tasks: httpd_conf_files.yml
  when: httpd_conf_files | default(False) == True
  
- include_tasks: start_apache.yml
  when: start_apache | default(False) == True
  
- include_tasks: stop_apache.yml
  when: stop_apache | default(False) == True
