---
- name:              Install pre-requisites
  yum:               name={{item}} state=present
  with_items:
    - unzip
    - tar
    - wget
  when:              (ansible_distribution == "RedHat") or (ansible_distribution == "CentOS")

- name:              Use Fix Pack ?
  set_fact:
    fp_files:    "{{ was_fp_files_fp9 }}"
    fp_version_check: "Updated to com.ibm.websphere.BASE.v85_{{ fp_version }}"
    was_fp_product_id:    "\"id='com.ibm.websphere.BASE.v85' version='{{ fp_version }}'\""
  when:              ( fp_version == was_fp_version_fp9 )

- name:              Is IIM Installed?
  command:           "egrep {{ imgr_product_id }} $HOME/var/ibm/InstallationManager/installed.xml"
  register:          iim_already_installed

- name:              Is WAS ND Installed?
  command:           "egrep {{ was_product_id }} $HOME/var/ibm/InstallationManager/installed.xml"
  register:          was_already_installed

- name:              Is Product already Installed?
  command:           "egrep {{ was_fp_product_id }} $HOME/var/ibm/InstallationManager/installed.xml"
  register:          version_already_installed
  ignore_errors:     true

- name:              Cleanup Binaries directory
  file:              path={{ staging_dir }} state=absent
  when:              version_already_installed.rc != 0
  ignore_errors:     true

- name:              Create Binaries directory
  file:              path={{ staging_dir }} state=directory mode=0755
  when:              version_already_installed.rc != 0

- name:              Create Logs directory
  file:              path={{ logs_dir }} state=directory mode=0755
  when:              version_already_installed.rc != 0

- name:              Download WAS Fixes
  get_url:
    url:             "{{ was_repository_url }}/{{ item.bf }}"
    dest:            "{{ staging_dir }}/{{ item.bf }}"
    mode:            0755
  with_items:        "{{ fp_files }}"
  when:              version_already_installed.rc != 0

- name:              Extract WAS Fixes
  unarchive:
    src:             "{{ staging_dir }}/{{ item.bf }}"
    dest:            "{{ staging_dir }}/"
    copy:            no
  with_items:        "{{ fp_files }}"
  when:              version_already_installed.rc != 0

- name:              Generate WAS Response file
  template:
    src:             "{{ fp_install_tpl_file }}"
    dest:            "{{ fp_install_rsp_file }}"
  when:              version_already_installed.rc != 0

- name:              Disable Repository on Installation Manager
  replace:
    path:            $HOME/var/ibm/InstallationManager/.settings/com.ibm.cic.agent.core.prefs
    regexp:          '(\s*)RepositoryIsOpen=true(\s*)'
    replace:         '\1RepositoryIsOpen=false\2'
    backup:          yes
  ignore_errors:     true

- name:              Install IBM WAS Fix Pack
  command:
    chdir={{ staging_dir }}
    {{ imgr_install_location }}/eclipse/tools/imcl -acceptLicense -sVP -log {{ fp_install_log_file }} input {{ fp_install_rsp_file }}
  register:          cout
  changed_when:      ( cout.stdout.find(fp_version_check) != -1)
  when:              version_already_installed.rc != 0

#- debug:            var=cout

- name:              Cleanup Binaries directory
  file:
    state:           absent
    path:            "{{ staging_dir }}"
  when:              version_already_installed.rc != 0
