---
- name:                 Verify if pid file
  shell:                ps -p `cat "{{ dmgr_profile_directory }}/logs/dmgr/dmgr.pid"`
  register:             dmgr_is_running
  ignore_errors:        true

- name:                 "Start Dmgr"
  command:              "{{ dmgr_bin_directory }}/startManager.sh"
  register:             cout
  changed_when:         cout.rc == 0
  when:                 dmgr_is_running.rc != 0